// File generated by FlutterFire CLI / Developer Options
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwJDnjyU0WQ8FZN7toybxJO8qUdLOzRI',
    appId: '1:574974313301:web:a44b77226b1446206165dc',
    messagingSenderId: '574974313301',
    projectId: 'repo-dog',
    authDomain: 'repo-dog.firebaseapp.com',
    storageBucket: 'repo-dog.firebasestorage.app',
    measurementId: 'G-5EMBLN9H6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmVDp7La4QLPWoGCYiIi4ASOo8uBOxD-I',
    appId: '1:574974313301:android:52276ee8fd5577b66165dc',
    messagingSenderId: '574974313301',
    projectId: 'repo-dog',
    storageBucket: 'repo-dog.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacEg8HLRg2w1ZwYdKXoFSGoBE0_ETK7I',
    appId: '1:574974313301:ios:c7b8007a2c3c1ba76165dc',
    messagingSenderId: '574974313301',
    projectId: 'repo-dog',
    storageBucket: 'repo-dog.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacEg8HLRg2w1ZwYdKXoFSGoBE0_ETK7I',
    appId: '1:574974313301:ios:c7b8007a2c3c1ba76165dc',
    messagingSenderId: '574974313301',
    projectId: 'repo-dog',
    storageBucket: 'repo-dog.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVwJDnjyU0WQ8FZN7toybxJO8qUdLOzRI',
    appId: '1:574974313301:web:ffb30a566a058b436165dc',
    messagingSenderId: '574974313301',
    projectId: 'repo-dog',
    authDomain: 'repo-dog.firebaseapp.com',
    storageBucket: 'repo-dog.firebasestorage.app',
    measurementId: 'G-JW1C2JL5HE',
  );
}
